package com.gaoxianglong.listviewdemo

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.ArrayAdapter
import android.widget.Toast
import kotlinx.android.synthetic.main.activity_main.*

class MainActivity : AppCompatActivity() {

    // 这里使用listOf()去定义一串集合 arrayOf()是定义一个数组
    private val data = listOf("Apple","Banana","Orange","Watermelon","Pear","Grape","Pineapple","Strawberry"
    ,"cherry","mango","Apple","Banana","Orange","Watermelon","Pear","Grape","Pineapple","Strawberry"
        ,"cherry","mango") // 数据
    private val fruitList = ArrayList<Fruit>()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
//        val adapter = ArrayAdapter(this, android.R.layout.simple_list_item_1, data) // 实例化一个适配器
        initFruit() // 初始化数据
        val adapter = FruitAdapter(this,R.layout.fruit_item,fruitList) // 使用我们自己的适配器
        list_view.adapter = adapter // 设置适配器
        list_view.setOnItemClickListener { parent, view, position, id ->
            val fruit = fruitList[position] // 获取到点击位置的Fruit实例
            Toast.makeText(this,fruit.name,Toast.LENGTH_SHORT).show()
        }
    }

    private fun initFruit() {
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
        fruitList.add(Fruit("Apple",R.drawable.apple_pic))
        fruitList.add(Fruit("Banana",R.drawable.banana_pic))
        fruitList.add(Fruit("Orange",R.drawable.orange_pic))
        fruitList.add(Fruit("Watermelon",R.drawable.watermelon_pic))
        fruitList.add(Fruit("Pear",R.drawable.pear_pic))
        fruitList.add(Fruit("Grape",R.drawable.grape_pic))
        fruitList.add(Fruit("Pineapple",R.drawable.pineapple_pic))
        fruitList.add(Fruit("Strawberry",R.drawable.strawberry_pic))
        fruitList.add(Fruit("cherry",R.drawable.cherry_pic))
        fruitList.add(Fruit("mango",R.drawable.mango_pic))
    }
}
